# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: make

    - name: Setup Tokens
      env:
        STRAVA_TOKENS: ${{ secrets.STRAVA_TOKENS }}
      run:
        echo "$STRAVA_TOKENS" > ./exampleConfig/stravaTokens.json

    - name: Test
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLUB_ID: ${{ secrets.CLUB_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: ./bin/hcvelo strava events --configDir ./exampleConfig --clientID "$CLIENT_ID" --clubID "$CLUB_ID" --clientSecret "$CLIENT_SECRET"

    - name: Update Secret
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 
        NEW_TOKEN=$(./bin/hcvelo strava tokens -configDir ./exampleConfig)
        gh secret set STRAVA_TOKENS -b "$NEW_TOKEN"
