# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: make

    - name: Setup Tokens
      env:
        STRAVA_TOKENS: ${{ secrets.STRAVA_TOKENS }}
      run:
        echo "$STRAVA_TOKENS" > ./exampleConfig/stravaTokens.json

    - name: Generate
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLUB_ID: ${{ secrets.CLUB_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        mkdir ./rides
        ./bin/hcvelo strava events --configDir ./exampleConfig --clientID "$CLIENT_ID" --clubID "$CLUB_ID" --clientSecret "$CLIENT_SECRET" --format md --output ./rides

    - name: Update Secret
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run:
        gh secret set STRAVA_TOKENS < ./exampleConfig/stravaTokens.json

    - name: Update Website
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh repo clone hcvelo/hcvelo.github.io
        rm ./hcvelo.github.io/content/rides/*
        cp -r ./rides/* ./hcvelo.github.io/content/rides
        cd ./hcvelo.github.io
        git add .
        git commit -m "Update Rides"
        git push
