# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '38 8,12,17,20 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: make

    - name: Setup Tokens
      env:
        STRAVA_TOKENS: ${{ secrets.STRAVA_TOKENS }}
      run:
        echo "$STRAVA_TOKENS" > ./exampleConfig/stravaTokens.json

    - name: Generate
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLUB_ID: ${{ secrets.CLUB_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        mkdir ./rides
        ./bin/hcvelo strava events --configDir ./exampleConfig --clientID "$CLIENT_ID" --clubID "$CLUB_ID" --clientSecret "$CLIENT_SECRET" --format md --output ./rides

    - name: Update Secret
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run:
        gh secret set STRAVA_TOKENS < ./exampleConfig/stravaTokens.json

    - name: Update Website
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://github.com/hcvelo/hcvelo.github.io.git
        rm ./hcvelo.github.io/content/rides/*
        cp -r ./rides/* ./hcvelo.github.io/content/rides
        cd ./hcvelo.github.io
        files_changed=$(git status -s)
        if [ -n "$files_changed" ]; then
          git remote set-url origin "https://hcvelo:$GH_TOKEN@github.com/hcvelo/hcvelo.github.io.git"
          git config user.email "hcvelo-bot@hcvelo.com"
          git config user.name "hcvelo"
          git add .
          git commit -m "Update Rides"
          git push -u origin main
        else
          echo "No changes to commit"
        fi
